import hashlib
import importlib.util
import json
import os
from pathlib import Path
import struct
import tarfile
import tempfile
import unittest
from unittest.mock import patch
import zlib

spec = importlib.util.spec_from_file_location('prepare_library', Path(__file__).with_name('prepare_library.py'))
prepare = importlib.util.module_from_spec(spec)
spec.loader.exec_module(prepare)

# A tiny generated byte fixture for raster-decoder tests, never a user image.
def png_fixture():
    def chunk(kind, data):
        return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data) & 0xffffffff)
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', 2, 2, 8, 2, 0, 0, 0))
            + chunk(b'IDAT', zlib.compress(b'\x00\xff\x00\x00\x00\xff\x00\x00\x00\x00\xff\xff\xff\xff'))
            + chunk(b'IEND', b''))

class PrepareLibraryTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix='portrait-prepare-test-')
        self.addCleanup(self.temp.cleanup)
        self.base = Path(self.temp.name).resolve()
        self.root = self.base / 'library'
        self.root.mkdir()
        (self.root / 'assets/images').mkdir(parents=True)
        (self.root / '.portrait-studio').mkdir()
        self.image = png_fixture()
        self.image_relative = 'assets/images/fixture.png'
        (self.root / self.image_relative).write_bytes(self.image)
        self.index = {'schemaVersion': 1, 'revision': 3, 'updatedAt': '2026-10-04T00:00:00Z', 'items': [
            {'id': 1, 'label': '完整名称', 'type': 'photo', 'prompts': {'en': 'Entire English prompt\nKeep every detail', 'zh': '完整中文提示词\n保留所有细节'},
             'image': 'fixture.png', 'imageRel': self.image_relative, 'revision': 1, 'size': len(self.image),
             'sha256': hashlib.sha256(self.image).hexdigest(), 'mime': 'image/png'}]}
        self.write_index()
        self.output = self.base / 'prepared.tar.gz'

    def write_index(self):
        (self.root / prepare.INDEX).write_text(json.dumps(self.index, ensure_ascii=False, indent=3) + '\n', encoding='utf-8')

    def run_prepare(self, count=1, revision=3):
        return prepare.prepare_library(str(self.root), str(self.output), count, revision)

    def snapshot(self):
        return {str(p.relative_to(self.root)): (p.stat().st_ino, p.stat().st_mtime_ns, p.stat().st_ctime_ns, p.read_bytes()) for p in self.root.rglob('*') if p.is_file()}

    def add_source_archive(self):
        token = '70668a95-bbc7-49f8-acba-9a8dd3ebc3b0'
        relative = '.portrait-studio/imports/' + token
        folder = self.root / relative
        folder.mkdir(parents=True)
        record = {'id': 1, 'image': 'fixture.png', 'label': 'Source label', 'prompt': 'Full original English\nAll original constraints', 'custom': {'deep': [1, '完整']}}
        manifest = (json.dumps({'images': [record], 'original_root_fields': {'retain': True}}, ensure_ascii=False, indent=4) + '\n').encode()
        (folder / 'manifest.json').write_bytes(manifest)
        (folder / 'mapping.json').write_text(json.dumps([{'index': 0, 'id': 1, 'targetId': 1, 'status': 'import'}]))
        (folder / 'source.json').write_text(json.dumps({'schemaVersion': 1, 'batchId': token}))
        (folder / 'report.json').write_text(json.dumps({'schemaVersion': 1, 'status': 'completed'}))
        translated = '完整衍生中文译文\n保留所有原始约束'
        self.index['items'][0]['prompts'] = {'en': record['prompt'], 'zh': translated}
        self.index['items'][0]['sourceMetadata'] = record
        self.index['items'][0]['sourceImport'] = {
            'archiveRel': relative, 'manifestSha256': hashlib.sha256(manifest).hexdigest(), 'sourceHash': self.index['items'][0]['sha256'],
            'sourceId': 1, 'recordIndex': 0, 'sourceFileName': 'fixture.png', 'sourceRelativePath': 'images/fixture.png', 'typeOrigin': 'selected-default',
            'derivedChinesePrompt': translated,
            'translationProvenance': {'kind': 'derived-translation', 'origin': 'assistant-translation', 'sourceLanguage': 'en', 'targetLanguage': 'zh',
                                      'sourcePromptField': 'prompt', 'sourcePromptSha256': hashlib.sha256(record['prompt'].encode()).hexdigest(),
                                      'translatedPromptSha256': hashlib.sha256(translated.encode()).hexdigest(), 'sourceId': 1, 'recordIndex': 0,
                                      'manifestSha256': hashlib.sha256(manifest).hexdigest()}}
        self.write_index()
        return folder, manifest

    def test_archive_exact_bytes_manifest_hashes_and_transient_exclusion(self):
        folder, original_manifest = self.add_source_archive()
        for directory in ('go-staging', 'go-transactions', 'pending'):
            path = self.root / '.portrait-studio' / directory
            path.mkdir()
            (path / 'transient.json').write_text('{"not_persistent":true}')
        (self.root / '.portrait-studio/go-store.lock').write_bytes(b'')
        before = self.snapshot()
        result = self.run_prepare()
        self.assertEqual(result['count'], 1)
        self.assertEqual(result['revision'], 3)
        self.assertEqual(result['files'], 6)
        self.assertEqual(before, self.snapshot())
        sidecar = json.loads(Path(result['manifest']).read_text())
        self.assertEqual(sidecar['root'], 'photo_repo')
        self.assertEqual(sidecar['archiveSha256'], hashlib.sha256(self.output.read_bytes()).hexdigest())
        with tarfile.open(self.output, 'r:gz') as archive:
            members = archive.getmembers()
            self.assertTrue(all(member.isfile() and member.name.startswith('photo_repo/') for member in members))
            self.assertFalse(any('lock' in member.name or 'staging' in member.name or 'transactions' in member.name or 'pending' in member.name for member in members))
            for item in sidecar['files']:
                raw = archive.extractfile(item['path']).read()
                self.assertEqual(len(raw), item['size'])
                self.assertEqual(hashlib.sha256(raw).hexdigest(), item['sha256'])
            archive_manifest = archive.extractfile('photo_repo/' + str(folder.relative_to(self.root)) + '/manifest.json').read()
            self.assertEqual(archive_manifest, original_manifest)
            self.assertEqual(archive.extractfile('photo_repo/' + prepare.INDEX).read(), (self.root / prepare.INDEX).read_bytes())

    def test_existing_output_and_sidecar_are_never_replaced(self):
        self.output.write_bytes(b'user-owned-data')
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertEqual(self.output.read_bytes(), b'user-owned-data')
        self.output.unlink()
        sidecar = Path(str(self.output) + '.manifest.json')
        sidecar.write_bytes(b'user-owned-manifest')
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())
        self.assertEqual(sidecar.read_bytes(), b'user-owned-manifest')

    def test_symlink_root_image_and_ancestor_rejected(self):
        linked_root = self.base / 'linked-root'
        linked_root.symlink_to(self.root, target_is_directory=True)
        with self.assertRaises(prepare.PreparationError):
            prepare.prepare_library(str(linked_root), str(self.output), 1, 3)
        outside = self.base / 'outside.png'
        outside.write_bytes(self.image)
        image_path = self.root / self.image_relative
        image_path.unlink()
        image_path.symlink_to(outside)
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertEqual(outside.read_bytes(), self.image)
        image_path.unlink()
        image_path.write_bytes(self.image)
        original = self.root / 'assets/images'
        relocated = self.root / 'images-original'
        original.rename(relocated)
        original.symlink_to(relocated, target_is_directory=True)
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_path_escape_missing_image_and_corrupt_bytes_rejected(self):
        self.index['items'][0]['imageRel'] = '../escape.png'
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.index['items'][0]['imageRel'] = self.image_relative
        self.write_index()
        image_path = self.root / self.image_relative
        image_path.unlink()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        damaged = self.image[:40]
        image_path.write_bytes(damaged)
        self.index['items'][0]['size'] = len(damaged)
        self.index['items'][0]['sha256'] = hashlib.sha256(damaged).hexdigest()
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_hash_mismatch_and_expected_count_revision_rejected(self):
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare(count=100)
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare(revision=2)
        self.index['items'][0]['sha256'] = '0' * 64
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_missing_source_archive_and_translation_tampering_rejected(self):
        folder, _ = self.add_source_archive()
        (folder / 'mapping.json').unlink()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        (folder / 'mapping.json').write_text('[{"index":0,"id":1,"targetId":1}]')
        self.index['items'][0]['sourceImport']['derivedChinesePrompt'] += '篡改'
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_target_prompt_binding_and_boolean_schema_rejected(self):
        self.add_source_archive()
        for language in ('en', 'zh'):
            original = self.index['items'][0]['prompts'][language]
            self.index['items'][0]['prompts'][language] = original + ' altered target'
            self.write_index()
            with self.assertRaises(prepare.PreparationError):
                self.run_prepare()
            self.index['items'][0]['prompts'][language] = original
        self.index['schemaVersion'] = True
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_source_path_type_and_null_metadata_rejected(self):
        self.add_source_archive()
        source = self.index['items'][0]['sourceImport']
        for key, bad in [('sourceFileName', '../outside.png'), ('sourceRelativePath', '../outside.png'), ('typeOrigin', 'unknown-origin')]:
            original = source[key]
            source[key] = bad
            self.write_index()
            with self.assertRaises(prepare.PreparationError):
                self.run_prepare()
            source[key] = original
        self.index['items'][0]['sourceMetadata'] = None
        self.index['items'][0]['sourceImport'] = None
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_index_string_types_and_output_parent_swap_rejected(self):
        self.index['updatedAt'] = 123
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.index['updatedAt'] = '2026-10-04T00:00:00Z'
        real_hash = self.index['items'][0]['sha256']
        self.index['items'][0]['sha256'] = int('1' * 64)
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.index['items'][0]['sha256'] = real_hash
        self.write_index()
        output_parent = self.base / 'output'
        output_parent.mkdir()
        moved_parent = self.base / 'output-original'
        self.output = output_parent / 'prepared.tar.gz'
        real_create = prepare.exclusive_file
        replaced = False
        def swap_parent(path, fd):
            nonlocal replaced
            if not replaced:
                output_parent.rename(moved_parent)
                output_parent.symlink_to(self.root, target_is_directory=True)
                replaced = True
            return real_create(path, fd)
        with patch.object(prepare, 'exclusive_file', swap_parent):
            with self.assertRaises(prepare.PreparationError):
                self.run_prepare()
        self.assertFalse((self.root / 'prepared.tar.gz').exists())
        self.assertFalse((self.root / 'prepared.tar.gz.manifest.json').exists())
        self.assertFalse((moved_parent / 'prepared.tar.gz').exists())
        self.assertFalse((moved_parent / 'prepared.tar.gz.manifest.json').exists())

    def test_image_prefix_case_and_raw_metadata_boolean_types_rejected(self):
        self.index['items'][0]['imageRel'] = 'ASSETS/IMAGES/fixture.png'
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.index['items'][0]['imageRel'] = self.image_relative
        self.write_index()
        folder, _ = self.add_source_archive()
        raw = json.loads((folder / 'manifest.json').read_text())
        raw['images'][0]['custom']['flag'] = True
        manifest = json.dumps(raw, ensure_ascii=False, indent=4).encode()
        (folder / 'manifest.json').write_bytes(manifest)
        source = self.index['items'][0]['sourceImport']
        source['manifestSha256'] = hashlib.sha256(manifest).hexdigest()
        source['translationProvenance']['manifestSha256'] = source['manifestSha256']
        self.index['items'][0]['sourceMetadata']['custom']['flag'] = 1
        self.write_index()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_null_translation_provenance_rejected(self):
        self.add_source_archive()
        source = self.index['items'][0]['sourceImport']
        source.pop('derivedChinesePrompt')
        source['translationProvenance'] = None
        self.write_index()
        before = self.snapshot()
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())
        self.assertEqual(before, self.snapshot())

    def test_source_change_during_decode_refuses_output(self):
        real_validate = prepare.RasterDecoder.validate
        def mutate(decoder, raw, expected_mime, label):
            result = real_validate(decoder, raw, expected_mime, label)
            self.index['updatedAt'] = 'externally-changed'
            self.write_index()
            return result
        with patch.object(prepare.RasterDecoder, 'validate', mutate):
            with self.assertRaises(prepare.PreparationError):
                self.run_prepare()
        self.assertFalse(self.output.exists())

    def test_output_inside_library_and_unknown_archive_files_rejected(self):
        with self.assertRaises(prepare.PreparationError):
            prepare.prepare_library(str(self.root), str(self.root / 'should-not-create.tar.gz'), 1, 3)
        folder, _ = self.add_source_archive()
        (folder / 'passwords.json').write_text('{"never":"bundle"}')
        with self.assertRaises(prepare.PreparationError):
            self.run_prepare()
        self.assertFalse(self.output.exists())

if __name__ == '__main__':
    unittest.main()
